<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>1.0.0.0</Version>
		<PackageVersion>1.0.0.0</PackageVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<InformationalVersion>1.0.0.0</InformationalVersion>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<LocalAppData>$([System.Environment]::GetFolderPath(SpecialFolder.LocalApplicationData))</LocalAppData>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>portable</DebugType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>none</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Pxoqxo.Resolver\Pxoqxo.Resolver.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Pxoqxo.Ext.Core">
			<HintPath>..\..\publish\Pxoqxo.Ext\em1.0\portable\Pxoqxo.Ext.Core.dll</HintPath>
		</Reference>
		<Reference Include="Pxoqxo.Quick">
			<HintPath>..\..\publish\Pxoqxo.Quick\em1.0\portable\Pxoqxo.Quick.dll</HintPath>
		</Reference>
		<Reference Include="Pxoqxo.UnitTest">
			<HintPath>..\..\publish\Pxoqxo.UnitTest\em1.0\portable\Pxoqxo.UnitTest.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
